
export const SAUNA_INVENTORY_ITEMS = [
  'Massage towels – white',
  'Massage towels – cream',
  'Massage towels – green',
  'Massage towels – purple',
  'Massage towels – black',
  'Sauna towels',
  'Blue lesos',
  'Green lesos',
  'Yellow lesos',
  'White bedsheets',
  'Massage bedcovers',
  'Cream headwraps',
  'Yellowish headwraps',
  'Shower caps',
  'Sandals (Lexus sneakers)',
  'Sitting mats',
  'Massage buckets',
  'Face towels',
  'Jago scrub',
  'Tumeric scrub',
  'Spa body scrub',
  'Massage oil',
  'Cups for dawa',
  'Sauna glasses',
  'Pillow',
  'Scrubbing gloves',
  'Pedicure towel',
];
